loader:
    use_n_scans : 1000

sensor:
    min_point_distance : 0.0
    max_point_distance : 100.0
    keep_points_ratio : 0.01
    min_return_intensity : -1.0

    estimate_point_times : false
    clockwise_lidar : false
    motion_compensation : true
    lidar_rpm : 600.0

aligner:
    local : false
    max_time_offset : 0.1
    angular_range : 0.5
    translation_range : 1.0
    max_evals : 200
    xtol : 0.0001
    knn_batch_size : 1000
    knn_k : 1
    local_knn_max_dist : 0.1
    global_knn_max_dist : 1.0
    time_cal : true
    output_pointcloud_path : "/home/udeer/data/InsGj/0408/result/cloudmap.ply"
    output_calibration_path : "/home/udeer/data/InsGj/0408/result/calibmap.txt"
    inital_guess:
      - 0.2
      - 0.3
      - 0.4
      - 0.0
      - 0.0
      - 0.1745327777777778
      - 0.0

# for combain clouds from lidar to odom
debug:
  x: -0.26
  y: 0.85
  z: 0.85
  roll: 0   # angle
  pitch: 0
  yaw: 90
  # for transform tum pose , T_target_source
  T_target_source:
   - -0.0283196
   - -0.999598
   - -0.0016717
   - -0.216226
   - 0.999582
   - -0.0283289
   - 0.00582084
   - 0.866041
   - -0.00586585
   - -0.00150616
   - 0.999982
   - -0.0175462
   - 0
   - 0
   - 0
   - 1
  evo_result: # from ref to est
    - 1.0
    - 0.0
    - 0.0
    - 0.0
    - 0.0
    - 1.0
    - 0.0
    - 0.0
    - 0.0
    - 0.0
    - 1.0
    - 0.0
    - 0.0
    - 0.0
    - 0.0
    - 1.0
    # - 0.99999617 
    # - -0.00184726
    # - 0.00205957
    # - -0.0403318
    # - 0.00187958
    # - 0.99987331
    # - -0.01580621
    # - 0.02858326
    # - -0.00203011
    # - 0.01581002
    # - 0.99987295
    # - -0.01844589
    # - 0.0
    # - 0.0
    # - 0.0
    # - 1





