loader:
    use_n_scans : 1000

sensor:
    min_point_distance : 0.0
    max_point_distance : 100.0
    keep_points_ratio : 0.01
    min_return_intensity : -1.0

    estimate_point_times : false
    clockwise_lidar : false
    motion_compensation : true
    lidar_rpm : 600.0

aligner:
    local : false
    max_time_offset : 0.1
    angular_range : 0.5
    translation_range : 1.0
    max_evals : 200
    xtol : 0.0001
    knn_batch_size : 1000
    knn_k : 1
    local_knn_max_dist : 0.1
    global_knn_max_dist : 1.0
    time_cal : true
    output_pointcloud_path : "/home/udeer/data/InsGj/0408/result/cloud.ply"
    output_calibration_path : "/home/udeer/data/InsGj/0408/result/calib.txt"
    inital_guess:
      - 0.0
      - 0.0
      - 0.0
      - 0.0
      - 0.0
      - 0.0
      - 0.0

# for combain clouds from lidar to odom
debug:
  # for transform tum pose , T_target_source
  T_target_source:
    - -0.0278213
    - -0.999591
    - 0.0065789
    - -0.216773
    - 0.999579
    - -0.0277653
    - 0.00846826
    - 0.866494
    - -0.00828213
    - 0.00681173
    - 0.999942
    - 0.0910535
    - 0
    - 0
    - 0
    - 1
    #unit
    # - 1.0
    # - 0.0
    # - 0.0
    # - 0.0
    # - 0.0
    # - 1.0
    # - 0.0
    # - 0.0
    # - 0.0
    # - 0.0
    # - 1.0
    # - 0.0
    # - 0.0
    # - 0.0
    # - 0.0
    # - 1.0

  evo_result: # from ref to est
    # unit
    - 1.0
    - 0.0
    - 0.0
    - 0.0
    - 0.0
    - 1.0
    - 0.0
    - 0.0
    - 0.0
    - 0.0
    - 1.0
    - 0.0
    - 0.0
    - 0.0
    - 0.0
    - 1.0
